apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/my-python-repo/python-app:v1.0.0
        ports:
        - containerPort: 8080